"""
Django settings for CAT project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%#ki+!uhu69)7j8sl@slpp9(=bdlz$e4iwgsv_(rxotvdp-59t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://*','http://*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'KITTEN.apps.KittenConfig',
    'storages', #for aws s3   
    
    
    
    
  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CAT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates') ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CAT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

AUTH_USER_MODEL = 'KITTEN.KittenUser'
LOGIN_URL = 'Login'
STATIC_URL = 'https://23202513s3.s3.eu-west-1.amazonaws.com/KITTEN/static/'
MEDIA_URL = '/images/'
MEDIA_ROOT = os.path.join( BASE_DIR, 'KITTEN/images')
STATIC_ROOT = os.path.join(BASE_DIR, 'KITTEN/static')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'testpf',
#         'USER': 'x23202513',
#         'PASSWORD': '23202513',
#         'HOST': 'testpf.chwlezgyi7rm.eu-west-1.rds.amazonaws.com',
#         'PORT': '3306',
#     }
    

# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dbdog',
        'USER': 'x23202513',
        'PASSWORD': '23202513',
        'HOST': 'dogsdb.chwlezgyi7rm.eu-west-1.rds.amazonaws.com',
        'PORT': '8080',
    }
    

 }

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_STORAGE_BUCKET_NAME = '23202513s3'
AWS_S3_REGION_NAME = 'eu-west-1'
# AWS_ACCESS_KEY_ID = 'ASIATUYJP7SUARE322G5'
# AWS_SECRET_ACCESS_KEY = 'NMv8dfETtoLRKjumkDqtH+bZCVtzFUn2g4zH0cYu'
# AWS_SESSION_TOKEN = 'IQoJb3JpZ2luX2VjENv//////////wEaCXVzLWVhc3QtMSJHMEUCIQDS68P+4BrI+eTk9O9n3c0ttqhE1pSRZUiQz13K0DRLhwIgMUafYl1PXcdgRh2VJ5HYxwpsEdPmkp2i8AHmyPeGRwkq/wMIIxADGgwyNTA3Mzg2Mzc5OTIiDP239cN8xa9NvgvK5SrcAxMfgUqQimuP3Qiag9LlZWGs3JASfmfa0LoZEBUTVEhIzMqKO+eireFQUYUeL4D/z5DbL3q13yzBnjyIg9+JFMGAzdVrQQeGNprD6xmuEMkERPqFyYp3pHjRhNu89x2kXzRgfmFlCUFYp8Mg8Xlrl1R9LK7aJmk/Vdjy5Ucv7AmR/noP/DK87J0w3FbevFSlOAxU+TGm+0/VATtiUpyHW/HfzFPlK8wdDHsKcU/+bAdN/0TV8OVR0lsJgjgxmxoxRXODbwCNhNZ02GcZ0NAP4Lz/ZPjv8OlO3wAkZWaklITPoYPM6VUMUAorO4xXmVip5PjQg5A2pbwrEzbgkLBy6Ov/K5z0n2RZxIjp77NikqnK4XxqWlph0dZxRNfDPhudhwhbDb4PXQBorJzCu+7x9LR3AFC2GV5p2lnNizTL3syBsIr6GVJAiiJfyE36EwB8YdK2hM7d8GHHNT3myQOVHakCIrGORsnitowMahS+dogSIrYZw0/gUcJY4Qdab2IyyGX/MlAXFSSxyuJSX+vMj1vusj7JF/rjKkyQXD87yGFuoZpiOVl/ED2/RtZ1nUUKZL54M3Bdk3sw2tKSpyQHR+vcD0LoImVkRjCOb0Zp6IjQi9lE3lj3DlgAUds/MNzFjLEGOqYB+Wd+uApMyMt0p2llmcxGlvHKdqdaeMsTwDwgDvo5gitKO9FvAcUiDVilatxAduYoiBuhuglVcWWRk77I6TBf96jvy6gzjx+CEEOR7ya8WF3MmXFMTcNJV4ZOZinbwc/vwwrCxb+5mqqbw1uwpczn5RStW9puIa2LzF6jCaSWrXQyBvWepnoKub2n/7kXHDQQofxeoK85AJAg8r72TFsr/o2qlqbJPA=='
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
STATIC_FILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'







